### ISSUE TITLE
Cursor jumping issues

### ISSUE THREAD

**Issue by aaronbhansen** [DockYard/ember-one-way-controls#102]
Just barely saw this project, installed the addon at 1.0. Changed text in the middle of the one-way-input and it was jumping to the end of the text. Downgraded to 0.9.1 and it no longer jumps when editing the cursor.

**Comment by martndemus** [comment]
Aaargh crap, did I really introduce the cursor jumping again? 😰

**Comment by adamdonahue** [comment]
I just spent two hours looking into this and now see this.  Yep, seems like cursor jumping is back, and here I thought I was doing something wrong.

**Comment by adamdonahue** [comment]
I tried reverting to 0.9.2, but now I'm not getting the one-way binding behavior.

My case is simple:

```javascript
 actions: {
    updateValue(propertyName, value) {
      for (const filter of DECIMAL_VALUE_FILTERS) {
        if (filter.test(value)) {
          return;
        }
      }
      this.set(propertyName, value);
    }
  }
```

The idea is if any invalid character is entered, it should be squashed.  My template:

```hbs
{{one-way-input
            value=value
            update=(action 'updateValue' 'value')
            }}
```

With version `v1.0.0` this works fine, except that the cursor jumps to the end if I edit in the middle of the string.

In version `v0.9.2` the cursor issue isn't there, but the input always changes even if the source value doesn't.

**Comment by adamdonahue** [comment]
(Note I tried using sanitizeValue in v1.0.0 but it wasn't getting executed.)

**Comment by seawatts** [comment]
I'm also seeing this issue with `v1.0.0`. Haven't tried other versions yet

**Comment by ffaubry** [comment]
+1

**Comment by lindyhopchris** [comment]
+1

**Comment by martndemus** [comment]
I published `1.0.1.`, that version should have fixed the issue, let me know if it doesn't.
Sorry for the delays.

**Comment by aaronbhansen** [comment]
Still doesn't fully work. The cursor doesn't jump, but typing "abcd" results in "acdb", after the first character it jumps back one position.

**Comment by seawatts** [comment]
Getting the same issue as @aaronbhansen

**Comment by martndemus** [comment]
This should now be fixed in `1.0.2`

**Comment by musaffa** [comment]
@martndemus Syncing value in `afterRender` queue seems like a hack and causing me some troubles. Isn't it fully solved since ember `2.3.1` as mentioned in the Readme? If it is, then should we not bypass that syncing if the ember version is greater or equal to 2.3.1?
